#!/bin/sh

set -eu

base=/etc/s6
tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' HUP INT QUIT TERM

for svcdir in "$base"/stage2/* ; do
  if test -r "$svcdir"/disabled ; then
    continue
  elif test -r "$svcdir"/instances ; then
    svcname=${svcdir##*/}
    outdir=${tmpdir}/${svcname}

    mkdir -p "$outdir"
    printf 'bundle\n' > "$outdir"/type
    sed -e "s/^/${svcname}@/" -e "s@/@-@g" "$svcdir"/instances > "$outdir"/contents

    while read -r instance ; do
      outdir=${tmpdir}/${svcname}@$(echo "${instance}" | tr / -)

      cp -pR "$svcdir" "$outdir"
      find "$outdir" -type f -exec sed -i "s@%I@${instance}@g" {} +
    done < "$svcdir"/instances
  else
    cp -pR "$svcdir" "$tmpdir"
  fi
done

for svcdir in "$tmpdir"/* ; do
  if test -r "$svcdir"/logdir ; then
    svcname=${svcdir##*/}
    logname="${svcname}-log"
    outdir=${tmpdir}/${logname}
    logdir="$(cat "$svcdir"/logdir)"

    mkdir -p "$outdir" "$logdir"
    printf '%s\n' "$logname" > "${svcdir}/producer-for"
    printf '%s\n' "$svcname" > "${outdir}/consumer-for"
    printf 'rc-fs\n' > "$outdir"/dependencies
    cat > "$outdir"/run << EOF
#!/bin/execlineb -P
if { install -dg nobody -m 0750 -o nobody /var/log/${logdir} }
umask 027
s6-setuidgid nobody
exec -c
s6-log t s1000000 n20 /var/log/${logdir}
EOF
    chmod +x "$outdir"/run
    printf 'longrun\n' > "$outdir"/type
  fi
done

# init rc db and start services
rm -rf "${base}/compiled"
s6-rc-compile -h nobody "${base}/compiled" "$tmpdir"
rm -rf "$tmpdir"
s6-rc-init /run/s6/service
s6-rc -u change rc-default
