#!/bin/bash

ulimit -n 1048576

#--storage-driver=overlay2 \
dockerd \
	--oom-score-adjust=-900 \
	--max-concurrent-downloads=5 \
	-H tcp://0.0.0.0:2375 \
	-H unix:///var/run/docker.sock \
	-p /run/dockerd.pid 2>&1
