#!/usr/bin/env bash

echo -n 0 >/proc/sys/kernel/grsecurity/chroot_caps
echo -n 0 >/proc/sys/kernel/grsecurity/chroot_deny_chmod
echo -n 0 >/proc/sys/kernel/grsecurity/chroot_deny_mknod
echo -n 0 >/proc/sys/kernel/grsecurity/chroot_deny_mount

ulimit -n 1048576

fdmove -c 2 1 exec dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -p /var/run/dockerd.pid
